Add a warning that `flatten` and `deny_unknown_fields` should not be mixed.
serde-rs/serde-rs.github.io pull request #120
Opened 2021-01-20 20:19 UTC by jonasbb

There are various bug reports about the interaction of `flatten` and
`deny_unknown_fields`. In the end they cannot really be combined, since
flatten does not consume the fields thus `deny_unknown_fields` will error
on them.

https://github.com/serde-rs/serde/issues/1957
https://github.com/serde-rs/serde/issues/1600
https://github.com/serde-rs/serde/issues/1547

2021-01-23 08:53 UTC, dtolnay requested changes

2021-01-23 08:53 UTC, dtolnay commented on _src/field-attrs.md
> +  *Note:* This attribute clashes with [`flatten`](attr-flatten.md) and might
If I am reading this correctly, this line says that `flatten` clashes with `flatten`. Clashing attributes is bad, but it's not quite that bad!

2021-01-23 08:54 UTC, dtolnay commented on _src/attr-flatten.md
> +*Note:* This attribute clashes with `flatten` and might make the struct
Same here -- this claims `flatten` clashes with `flatten`.

2021-01-24 14:12 UTC, jonasbb commented
@dtolnay Thank you for the comment. Yes I messed up the description while hastily creating this PR. I fixed the mistake.

2021-01-25 05:52 UTC, dtolnay approved these changes
Thanks!

2021-01-25 05:53 UTC, merged